enum ACTIONS {
  TOGGLE_TIMER_RUNNING_STATE,
  RESET_TIMER_LENGTH,
  TOGGLE_TIMER_TYPE_STATE,
  UPDATE_TIMER_STATE,
  UPDATE_BREAK_LENGTH,
  UPDATE_SESSION_LENGTH,
  UPDATE_TIMER_LENGTH,
};

export default ACTIONS;
