export const TOGGLE_TIMER_RUNNING_STATE = 'TOGGLE_TIMER_RUNNING_STATE';
export const RESET_TIMER_LENGTH = 'RESET_TIMER_LENGTH';
export const TOGGLE_TIMER_TYPE_STATE = 'TOGGLE_TIMER_TYPE_STATE';
export const UPDATE_TIMER_STATE = 'UPDATE_TIMER_STATE';
export const UPDATE_BREAK_LENGTH = 'UPDATE_BREAK_LENGTH';
export const UPDATE_SESSION_LENGTH = 'UPDATE_SESSION_LENGTH';
export const UPDATE_TIMER_LENGTH = 'UPDATE_TIMER_LENGTH';

export * as default from './ACTIONS';
