export const TOGGLE_TIMER_STATE = 'TOGGLE_TIMER_STATE';
export const RESET_TIMER_LENGTH = 'RESET_TIMER_LENGTH';
export const UPDATE_BREAK_LENGTH = 'UPDATE_BREAK_LENGTH';
export const UPDATE_SESSION_LENGTH = 'UPDATE_SESSION_LENGTH';
export const UPDATE_TIMER_LENGTH = 'UPDATE_TIMER_LENGTH';
